spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.220.128:5432/board_db
    username: board_user
    password: board_pass

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.board.backend

server:
  port: 8080